############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Join ECEA"
url = "about/"
weight = 2

[[main]]
name = "Latest News"
url = "blog/"
weight = 3

[[main]]
name = "Clubs"
url = "clubs/"
weight = 4

[[main]]
weight = 5
name = "Enduro"
hasChildren = true

  [[main]]
  parent = "Enduro"
  name = "Enduro Series Registration"
  url = "faq/"
  weight = 1

  [[main]]
  parent = "Enduro"
  name = "Enduro Event Registration"
  url = "faq/"
  weight = 2

  [[main]]
  parent = "Enduro"
  name = "Enduro Schedule"
  url = "faq/"
  weight = 3

  [[main]]
  parent = "Enduro"
  name = "Enduro Results"
  url = "faq/"
  weight = 4

  [[main]]
  parent = "Enduro"
  name = "Enduro Championship Results"
  url = "faq/"
  weight = 5

[[main]]
weight = 6
name = "Harescramble"
hasChildren = true

  [[main]]
  parent = "Harescramble"
  name = "Harescramble Series Registration"
  url = "faq/"
  weight = 1

  [[main]]
  parent = "Harescramble"
  name = "Harescramble Event Registration"
  url = "faq/"
  weight = 2

  [[main]]
  parent = "Harescramble"
  name = "Harescramble Schedule"
  url = "faq/"
  weight = 3

  [[main]]
  parent = "Harescramble"
  name = "Harescramble Results"
  url = "faq/"
  weight = 4

  [[main]]
  parent = "Harescramble"
  name = "Harescramble Championship Results"
  url = "faq/"
  weight = 5

[[main]]
weight = 7
name = "FastKIDZ"
hasChildren = true

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Series Registration"
  url = "faq/"
  weight = 1

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Event Registration"
  url = "faq/"
  weight = 2

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Schedule"
  url = "faq/"
  weight = 3

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Results"
  url = "faq/"
  weight = 4

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Championship Results"
  url = "faq/"
  weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 8


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Project"
url = "project/"
weight = 3

[[footer]]
name = "Service"
url = "service/"
weight = 4

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7
