############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Join ECEA"
url = "get-started/"
weight = 2

[[main]]
name = "Latest News"
url = "blog/"
weight = 3

[[main]]
name = "Schedule"
url = "events/"
weight = 3

[[main]]
name = "Clubs"
url = "clubs/"
weight = 4


[[main]]
weight = 5
name = "Enduro"
hasChildren = true

  [[main]]
  parent = "Enduro"
  name = "Enduro Hub"
  url = "series/enduro"
  weight = 1

  [[main]]
  parent = "Enduro"
  name = "Enduro Series Registration"
  url = "https://www.moto-tally.com/ECEA/Enduro/SeriesRegistration.aspx"
  weight = 1

  [[main]]
  parent = "Enduro"
  name = "Enduro Event Registration"
  url = "https://www.moto-tally.com/ECEA/Enduro/PreEntry.aspx"
  weight = 2

  [[main]]
  parent = "Enduro"
  name = "Enduro Schedule"
  url = "events?type=enduro"
  weight = 3

  [[main]]
  parent = "Enduro"
  name = "Enduro Results"
  url = "https://www.moto-tally.com/ECEA/Enduro/Results.aspx"
  weight = 4

  [[main]]
  parent = "Enduro"
  name = "Enduro Championship Results"
  url = "https://www.moto-tally.com/ECEA/Enduro/Standings.aspx"
  weight = 5

  [[main]]
  parent = "Enduro"
  name = "Enduro Membership List"
  url = "https://www.moto-tally.com/ECEA/Enduro/MemberList.aspx"
  weight = 6

  [[main]]
  parent = "Enduro"
  name = "Enduro Team Results"
  url = "team_results"
  weight = 5

[[main]]
weight = 6
name = "Hare Scramble"
hasChildren = true

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Hub"
  url = "series/harescramble"
  weight = 1

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Series Registration"
  url = "https://www.moto-tally.com/ECEA/ECEA/SeriesRegistration.aspx"
  weight = 1

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Event Registration"
  url = "https://www.moto-tally.com/ECEA/ECEA/PreEntry.aspx"
  weight = 2

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Schedule"
  url = "events?type=hare-scramble"
  weight = 3

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Results"
  url = "https://www.moto-tally.com/ECEA/ECEA/Results.aspx"
  weight = 4

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Championship Results"
  url = "https://www.moto-tally.com/ECEA/ECEA/Standings.aspx"
  weight = 5

  [[main]]
  parent = "Hare Scramble"
  name = "Hare Scramble Membership List"
  url = "https://www.moto-tally.com/ECEA/ECEA/MemberList.aspx"
  weight = 6

[[main]]
weight = 7
name = "FastKIDZ"
hasChildren = true

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Hub"
  url = "series/fastkidz"
  weight = 1

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Series Registration"
  url = "https://www.moto-tally.com/ECEA/ECEA_PWY/SeriesRegistration.aspx"
  weight = 1

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Event Registration"
  url = "http://www.moto-tally.com/ECEA/ECEA_PWY/PreEntry.aspx"
  weight = 2

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Schedule"
  url = "events?type=fastkidz"
  weight = 3

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Results"
  url = "http://www.moto-tally.com/ECEA/ECEA_PWY/Results.aspx"
  weight = 4

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Championship Results"
  url = "http://www.moto-tally.com/ECEA/ECEA_PWY/Standings.aspx"
  weight = 5

  [[main]]
  parent = "FastKIDZ"
  name = "FastKIDZ Membership List"
  url = "http://www.moto-tally.com/ECEA/ECEA_PWY/MemberList.aspx"
  weight = 6

[[main]]
name = "Dual Sport"
url = "series/dual-sport"
weight = 8

[[main]]
weight = 9
name = "Resources"
hasChildren = true

  [[main]]
  parent = "Resources"
  name = "Welcome Book"
  url = "documents/ecea-welcome-book.pdf"

  [[main]]
  parent = "Resources"
  name = "Rule Book"
  url = "documents/ecea-rulebook-current.pdf"

  [[main]]
  parent = "Resources"
  name = "Protest Form"
  url = "documents/ecea-protest-form.pdf"

  [[main]]
  parent = "Resources"
  name = "Rule Proposals"
  url = "documents/ecea-rule-proposal-form.pdf"

  [[main]]
  parent = "Resources"
  name = "Enduro Team Registration Form"
  url = "documents/ecea-enduro-team-signup.pdf"

  [[main]]
  parent = "Resources"
  name = "Statement of Responsibility"
  url = "documents/ecea-enduro-statement-of-responsibility.pdf"

  [[main]]
  parent = "Resources"
  name = "Hall of Fame Nomination"
  url = "documents/ecea-hall-of-fame-nomination-form.pdf"

  [[main]]
  parent = "Resources"
  name = "Rule Proposals"
  url = "documents/ecea-rule-proposal-form.pdf"

  [[main]]
  parent = "Resources"
  name = "Racing Protest Log"
  url = "documents/ecea-club-referee-protest-log.pdf"

   [[main]]
  parent = "Resources"
  name = "Advancement Petition"
  url = "documents/ecea-advancement-petition-form.pdf"

  [[main]]
  parent = "Resources"
  name = "How to Protest"
  url = "documents/ecea-protest-procedure-flow-chart.pdf"

[[main]]
name = "Contact"
url = "contact/"
weight = 10

# footer menu
[[footer]]
name = "About"
url = "get-started/"
weight = 2

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7
