backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/english/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Blog Post Image"
        name: "image"
        widget: "image"
        media_library:
          config:
            media_folder: "static/images/blog"
      - {label: "Background Image", name: "bg_image", widget: "hidden", default: "images/feature-bg.jpg"}
      - label: "Categories"
        name: "categories"
        widget: "select"
        options: ["Announcement", "News", "On Your Minute"]
        multiple: true
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Blog Entry Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "content-pages"
    label: "Content Pages"
    files:
      - label: "FAQ"
        name: "faq"
        file: "content/english/faq.md"
        fields:
          - {label: "Last Modified Date", name: "date", widget: "datetime"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contacts"
        name: "contacts"
        file: "content/english/contact.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "enduro-event" # Used in routes, e.g., /admin/collections/blog
    label: "Enduro Event" # Used in the UI
    folder: "content/english/events/enduro" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{event_type}}-{{club}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tag Line", name: "description", widget: "string"}
      - {label: "Club", name: "club", widget: "select", multiple: true,
          options: ["BER", "CDR", "CJCR", "DVTR", "GMER", "HMDR", "IDR", "MCI", "MMC", "OCCR", "RORR", "RRMC", "SJER", "SPER", "STER", "TCSMC", "VFTR"]
        }
      - {label: "Event Date", name: "event_datetime", widget: "datetime"}
      - {label: "Address", name: "location", widget: "string"}
      - {label: "Event Type", name: "event_type", widget: "hidden", default: "Enduro"}
      - {label: "Event Format", name: "event_format", widget: "select",
          options: ["Time Keeping", "Restart", "Sprint Enduro", "National Enduro", "Other"]
        }
      - {label: "Event Series", name: "event_series", widget: "hidden", default: "ECEA Enduro Championship Series"}
      - {label: "Closed course?", name: "closed_course", widget: "select",
          options: ["Yes", "No"]
        }
      - label: "Starting Grid URL"
        name: "start_grid"
        widget: "string"
        required: false
      - label: "Key Time"
        name: "key_time"
        widget: "datetime"
      - label: "Check In Time"
        name: "check_in_time"
        widget: "datetime"
        hint: "What time does check-in open in the morning?"
      - label: Pre-Entry Date
        name: "registration_date"
        widget: "datetime"
        hint: "What day and time will pre-entry open?"
        required: false
      - {label: "Description and information about event", name: "body", widget: "markdown"}
      - label: "Club Logo"
        name: "preview-image"
        widget: "image"
        media_library:
          config:
            media_folder: "/static/images/logos/clubs/"
      - {label: "Background Image", name: "bg-image", widget: "hidden", default: "static/images/feature-bg.jpg"}
      - label: "Flyer Image"
        name: "flyer"
        widget: "image"
        required: false
        media_library:
          config:
            media_folder: "static/images/events/flyers"
      - label: "Route Sheet, Confirmation Sheet, etc"
        name: "attachments"
        widget: "object"
        required: false
        hint: "These files are not required yet. You can come back and add them later."
        fields:
        - label: "Confirmation Sheet"
          name: "attachment1"
          widget: "object"
          required: false
          fields:
            - label: "Label"
              name: "label"
              widget: "string"
              default: "Confirmation Sheet"
            - label: "File"
              name: "path"
              widget: "file"
              media_library:
                config:
                  media_folder: "static/documents/events/attachments/events"
        - label: "Route Sheet"
          name: "attachment2"
          widget: "object"
          required: false
          fields:
            - label: "Label"
              name: "label"
              widget: "string"
              default: "Route Sheet"
            - label: "File"
              name: "path"
              widget: "file"
              media_library:
                config:
                  media_folder: "static/events/attachments/events"
        - label: "Other Document"
          name: "attachment3"
          widget: "object"
          required: false
          fields:
            - label: "Label"
              name: "label"
              widget: "string"
            - label: "File"
              name: "path"
              widget: "file"
              media_library:
                config:
                  media_folder: "static/events/attachments/events"
        - label: "Other Document"
          name: "attachment4"
          widget: "object"
          required: false
          fields:
            - label: "Label"
              name: "label"
              widget: "string"
            - label: "File"
              name: "path"
              widget: "file"
              media_library:
                config:
                  media_folder: "static/events/attachments/events"